// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmtfygvqepjwzfxxcqnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdGZ5Z3ZxZXBqd3pmeHhjcW56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTcwODEsImV4cCI6MjA2NzEzMzA4MX0.bRgyHnIdNMO9IYy1bJbN3on8h_iy0zgrdTrS9qRau0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});